import { Platform } from "react-native";

const tintColorLight = "#10B981";
const tintColorDark = "#10B981";

export const Colors = {
  light: {
    primary: "#10B981",
    primaryLight: "#34D399",
    primaryDark: "#059669",
    secondary: "#00B2FF",
    background: "#FFFFFF",
    backgroundGradientStart: "#FFFFFF",
    backgroundGradientEnd: "#F0F4FF",
    surface: "#F5F8FC",
    surfaceElevated: "#FFFFFF",
    text: "#1A1A2E",
    textSecondary: "#8E8E93",
    textTertiary: "#AEAEB2",
    buttonText: "#FFFFFF",
    success: "#00D856",
    error: "#FF6B6B",
    warning: "#FFC629",
    border: "#E0E8F0",
    borderLight: "#F0F4F8",
    online: "#00D856",
    tabIconDefault: "#8E8E93",
    tabIconSelected: tintColorLight,
    link: "#10B981",
    backgroundRoot: "#FFFFFF",
    backgroundDefault: "#FFFFFF",
    backgroundSecondary: "#F5F8FC",
    backgroundTertiary: "#E0E8F0",
    pass: "#FF6B6B",
    superLike: "#00B2FF",
    like: "#10B981",
    rewind: "#FFC629",
    boost: "#9B59B6",
    inputBackground: "#F5F8FC",
    inputBorder: "#E0E8F0",
    cardBackground: "#FFFFFF",
    cardShadow: "rgba(0, 0, 0, 0.08)",
    overlay: "rgba(0, 0, 0, 0.5)",
    divider: "#E0E8F0",
    settingsSectionBg: "#F5F8FC",
    settingsItemBg: "#FFFFFF",
    modalBackground: "#FFFFFF",
    accentGradientStart: "#10B981",
    accentGradientEnd: "#34D399",
    card: "#FFFFFF",
    surfaceSecondary: "#F0F4F8",
  },
  dark: {
    primary: "#10B981",
    primaryLight: "#34D399",
    primaryDark: "#059669",
    secondary: "#00B2FF",
    background: "#0D1117",
    backgroundGradientStart: "#0D1117",
    backgroundGradientEnd: "#161B22",
    surface: "#161B22",
    surfaceElevated: "#21262D",
    text: "#FFFFFF",
    textSecondary: "#8B949E",
    textTertiary: "#6E7681",
    buttonText: "#FFFFFF",
    success: "#00D856",
    error: "#FF6B6B",
    warning: "#FFC629",
    border: "#30363D",
    borderLight: "#21262D",
    online: "#00D856",
    tabIconDefault: "#8B949E",
    tabIconSelected: tintColorDark,
    link: "#10B981",
    backgroundRoot: "#0D1117",
    backgroundDefault: "#0D1117",
    backgroundSecondary: "#161B22",
    backgroundTertiary: "#21262D",
    pass: "#FF6B6B",
    superLike: "#00B2FF",
    like: "#10B981",
    rewind: "#FFC629",
    boost: "#9B59B6",
    inputBackground: "#161B22",
    inputBorder: "#30363D",
    cardBackground: "#161B22",
    cardShadow: "rgba(0, 0, 0, 0.3)",
    overlay: "rgba(0, 0, 0, 0.7)",
    divider: "#30363D",
    settingsSectionBg: "#161B22",
    settingsItemBg: "#21262D",
    modalBackground: "#161B22",
    accentGradientStart: "#10B981",
    accentGradientEnd: "#34D399",
    card: "#161B22",
    surfaceSecondary: "#21262D",
  },
};

export const Spacing = {
  xxs: 2,
  xs: 4,
  sm: 8,
  s: 8,
  md: 12,
  m: 12,
  lg: 16,
  l: 16,
  xl: 24,
  xxl: 32,
  "2xl": 32,
  xxxl: 48,
  huge: 64,
  inputHeight: 56,
  buttonHeight: 56,
  iconButton: 48,
  tabBarHeight: 65,
  headerHeight: 100,
};

export const BorderRadius = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  l: 16,
  xl: 24,
  xxl: 28,
  "2xl": 28,
  full: 9999,
};

export const Typography = {
  h1: {
    fontSize: 32,
    fontWeight: "700" as const,
    lineHeight: 38,
    letterSpacing: -0.5,
  },
  h2: {
    fontSize: 24,
    fontWeight: "700" as const,
    lineHeight: 30,
    letterSpacing: -0.3,
  },
  h3: {
    fontSize: 20,
    fontWeight: "600" as const,
    lineHeight: 26,
    letterSpacing: -0.2,
  },
  subtitle: {
    fontSize: 18,
    fontWeight: "600" as const,
    lineHeight: 24,
  },
  body: {
    fontSize: 16,
    fontWeight: "400" as const,
    lineHeight: 22,
  },
  bodyBold: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 22,
  },
  caption: {
    fontSize: 14,
    fontWeight: "400" as const,
    lineHeight: 18,
  },
  captionBold: {
    fontSize: 14,
    fontWeight: "600" as const,
    lineHeight: 18,
  },
  small: {
    fontSize: 12,
    fontWeight: "400" as const,
    lineHeight: 16,
  },
  smallBold: {
    fontSize: 12,
    fontWeight: "600" as const,
    lineHeight: 16,
  },
  tiny: {
    fontSize: 10,
    fontWeight: "500" as const,
    lineHeight: 14,
    letterSpacing: 0.5,
  },
  h4: {
    fontSize: 16,
    fontWeight: "600" as const,
    lineHeight: 22,
    letterSpacing: -0.1,
  },
  link: {
    fontSize: 14,
    fontWeight: "500" as const,
    lineHeight: 20,
    textDecorationLine: "underline" as const,
  },
};

export const Shadow = {
  small: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  medium: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 4,
  },
  large: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  card: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  button: {
    shadowColor: "#4A90D9",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
};

export const Elevation = {
  level1: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    ...Shadow.small,
  },
  level2: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    ...Shadow.medium,
  },
  level3: {
    backgroundColor: "rgba(255, 255, 255, 1)",
    ...Shadow.large,
  },
};

export const Fonts = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
